title: Julie(Duyi) Liu
logo: /assets/img/headshot_circle.png
description: 
<a href="https://www.linkedin.com/in/julieliu2024/">View My LinkedIn Profile</a> 
# show_downloads: false
theme: jekyll-theme-minimal
